
	<img id="AF_AZUL" src="frontend/advisor/shapes/AF_AZUL.png" hidden>
	<img id="Binding_AZUL" src="frontend/advisor/shapes/Binding_AZUL.png" hidden>
	<img id="Datatype_AZUL" src="frontend/advisor/shapes/Datatype_AZUL.png" hidden>
	<img id="Equip_AZUL" src="frontend/advisor/shapes/Equip_AZUL.png" hidden>
	<img id="FORWARDING_AZUL" src="frontend/advisor/shapes/FORWARDING_AZUL.png" hidden>
	<img id="FWR_RULE_AZUL" src="frontend/advisor/shapes/FWR_RULE_AZUL.png" hidden>
	<img id="Input_AZUL" src="frontend/advisor/shapes/Input_AZUL.png" hidden>
	<img id="INT_IN_AZUL" src="frontend/advisor/shapes/INT_IN_AZUL.png" hidden>
	<img id="INT_OUT_AZUL" src="frontend/advisor/shapes/INT_OUT_AZUL.png" hidden>
	<img id="Layer_AZUL" src="frontend/advisor/shapes/Layer_AZUL.png" hidden>
	<img id="LPF_AZUL" src="frontend/advisor/shapes/LPF_AZUL.png" hidden>
	<img id="Matrix_AZUL" src="frontend/advisor/shapes/Matrix_AZUL.png" hidden>
	<img id="Output_AZUL" src="frontend/advisor/shapes/Output_AZUL.png" hidden>
	<img id="PM_AZUL" src="frontend/advisor/shapes/PM_AZUL.png" hidden>
	<img id="Process_AZUL" src="frontend/advisor/shapes/Process_AZUL.png" hidden>
	<img id="RP_AZUL" src="frontend/advisor/shapes/RP_AZUL.png" hidden>
	<img id="SITE_AZUL" src="frontend/advisor/shapes/SITE_AZUL.png" hidden>
	<img id="SN_AZUL" src="frontend/advisor/shapes/SN_AZUL.png" hidden>
	<img id="TE_AZUL" src="frontend/advisor/shapes/TE_AZUL.png" hidden>
	<img id="TF_AZUL" src="frontend/advisor/shapes/TF_AZUL.png" hidden>

	<img id="AF_ROXO" src="frontend/advisor/shapes/AF_ROXO.png" hidden>
	<img id="Binding_ROXO" src="frontend/advisor/shapes/Binding_ROXO.png" hidden>
	<img id="Datatype_ROXO" src="frontend/advisor/shapes/Datatype_ROXO.png" hidden>
	<img id="Equip_ROXO" src="frontend/advisor/shapes/Equip_ROXO.png" hidden>
	<img id="FORWARDING_ROXO" src="frontend/advisor/shapes/FORWARDING_ROXO.png" hidden>
	<img id="FWR_RULE_ROXO" src="frontend/advisor/shapes/FWR_RULE_ROXO.png" hidden>
	<img id="Input_ROXO" src="frontend/advisor/shapes/Input_ROXO.png" hidden>
	<img id="INT_IN_ROXO" src="frontend/advisor/shapes/INT_IN_ROXO.png" hidden>
	<img id="INT_OUT_ROXO" src="frontend/advisor/shapes/INT_OUT_ROXO.png" hidden>
	<img id="Layer_ROXO" src="frontend/advisor/shapes/Layer_ROXO.png" hidden>
	<img id="LPF_ROXO" src="frontend/advisor/shapes/LPF_ROXO.png" hidden>
	<img id="Matrix_ROXO" src="frontend/advisor/shapes/Matrix_ROXO.png" hidden>
	<img id="Output_ROXO" src="frontend/advisor/shapes/Output_ROXO.png" hidden>
	<img id="PM_ROXO" src="frontend/advisor/shapes/PM_ROXO.png" hidden>
	<img id="Process_ROXO" src="frontend/advisor/shapes/Process_ROXO.png" hidden>
	<img id="RP_ROXO" src="frontend/advisor/shapes/RP_ROXO.png" hidden>
	<img id="SITE_ROXO" src="frontend/advisor/shapes/SITE_ROXO.png" hidden>
	<img id="SN_ROXO" src="frontend/advisor/shapes/SN_ROXO.png" hidden>
	<img id="TE_ROXO" src="frontend/advisor/shapes/TE_ROXO.png" hidden>
	<img id="TF_ROXO" src="frontend/advisor/shapes/TF_ROXO.png" hidden>
	
	<img id="AF_VERDE" src="frontend/advisor/shapes/AF_VERDE.png" hidden>
	<img id="Binding_VERDE" src="frontend/advisor/shapes/Binding_VERDE.png" hidden>
	<img id="Datatype_VERDE" src="frontend/advisor/shapes/Datatype_VERDE.png" hidden>
	<img id="Equip_VERDE" src="frontend/advisor/shapes/Equip_VERDE.png" hidden>
	<img id="FORWARDING_VERDE" src="frontend/advisor/shapes/FORWARDING_VERDE.png" hidden>
	<img id="FWR_RULE_VERDE" src="frontend/advisor/shapes/FWR_RULE_VERDE.png" hidden>
	<img id="Input_VERDE" src="frontend/advisor/shapes/Input_VERDE.png" hidden>
	<img id="INT_IN_VERDE" src="frontend/advisor/shapes/INT_IN_VERDE.png" hidden>
	<img id="INT_OUT_VERDE" src="frontend/advisor/shapes/INT_OUT_VERDE.png" hidden>
	<img id="Layer_VERDE" src="frontend/advisor/shapes/Layer_VERDE.png" hidden>
	<img id="LPF_VERDE" src="frontend/advisor/shapes/LPF_VERDE.png" hidden>
	<img id="Matrix_VERDE" src="frontend/advisor/shapes/Matrix_VERDE.png" hidden>
	<img id="Output_VERDE" src="frontend/advisor/shapes/Output_VERDE.png" hidden>
	<img id="PM_VERDE" src="frontend/advisor/shapes/PM_VERDE.png" hidden>
	<img id="Process_VERDE" src="frontend/advisor/shapes/Process_VERDE.png" hidden>
	<img id="RP_VERDE" src="frontend/advisor/shapes/RP_VERDE.png" hidden>
	<img id="SITE_VERDE" src="frontend/advisor/shapes/SITE_VERDE.png" hidden>
	<img id="SN_VERDE" src="frontend/advisor/shapes/SN_VERDE.png" hidden>
	<img id="TE_VERDE" src="frontend/advisor/shapes/TE_VERDE.png" hidden>
	<img id="TF_VERDE" src="frontend/advisor/shapes/TF_VERDE.png" hidden>
	
	<img id="Equip_LARANJA" src="frontend/advisor/shapes/Equip_LARANJA.png" hidden>
	<img id="PM_LARANJA" src="frontend/advisor/shapes/PM_LARANJA.png" hidden>
	<img id="RP_LARANJA" src="frontend/advisor/shapes/RP_LARANJA.png" hidden>