package br.com.padtec.common.queries;

public enum OntPropertyEnum {
	OBJECT_PROPERTY, DATA_PROPERTY, TRANSITIVE_PROPERTY, SYMMETRIC_PROPERTY, FUNCTIONAL_PROPERTY, ANNOTATION_PROPERTY, INVERSE_FUNCTIONAL_PROPERTY
}
