package br.com.padtec.common.types;

public enum OntClassEnum {
	INTERSECTION_CLASS, ENUMERATED_CLASS, COMPLEMENT_CLASS, UNION_CLASS, 
	RESTRICTION, QUALIFIED_RESTRICTION, CARDINALITY_RESTRICTION, SOME_VALUES_FROM_RESTRICTION, ALL_VALUES_FROM_RESTRICTION, HAS_VALUES_RESTRICTION,
	MIN_CARDINALITY_RESTRICTION, MAX_CARDINALITY_RESTRICTION, 
}
